exclude: migrations
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]
        args: [--config=pyproject.toml]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.256"
    hooks:
      - id: ruff
