name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "poetry"

      - name: Prepare version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          poetry version $VERSION

      - name: Publish package
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
